name: Minimal Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # Deploy from main branch
          branch: main
          # Force deployment
          force: true
          publish_dir: ./public
