name: Skip GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Skip Deployment
        run: echo "Skipping GitHub Pages deployment as per user request."
